# Generated by Django 4.2.8 on 2025-09-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_terminal', models.CharField(max_length=200)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_terminal', models.CharField(max_length=200)),
                ('distance_km', models.PositiveIntegerField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('intermediate_stops', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='companies.company')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
                'db_table': 'trips_route',
                'ordering': ['origin_city', 'destination_city'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('BOARDING', 'Boarding'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DELAYED', 'Delayed')], default='SCHEDULED', max_length=20)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('available_seats', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('conductor_name', models.CharField(blank=True, max_length=100)),
                ('conductor_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.bus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.company')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.route')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips_trip',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TripPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_season_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('early_bird_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('final_base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_bird_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Pricing',
                'verbose_name_plural': 'Trip Pricing',
                'db_table': 'trips_pricing',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', 'departure_date'], name='trips_trip_company_d5b562_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'departure_date'], name='trips_trip_route_i_b59b87_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='trips_trip_status_259ca6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('company', 'origin_city', 'destination_city')},
        ),
    ]
