# Generated by Django 4.2.8 on 2025-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookutu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='registration_enabled',
            new_name='allow_company_registration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='booking_confirmation_message',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='facebook_url',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='favicon',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='maintenance_message',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='welcome_message',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='currency',
            field=models.CharField(default='UGX', max_length=3),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='default_commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='require_company_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_booking_confirmations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='send_payment_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='platform_description',
            field=models.TextField(default='Book bus tickets easily and securely across Uganda'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='platform_tagline',
            field=models.CharField(default='Your Trusted Bus Booking Platform', max_length=200),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='support_phone',
            field=models.CharField(default='+256700000000', max_length=20),
        ),
        migrations.AlterModelTable(
            name='systemsettings',
            table='bookutu_system_settings',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
