# Generated by Django 4.2.7 on 2025-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookutu', '0002_rename_registration_enabled_systemsettings_allow_company_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='adverts/')),
                ('link_url', models.URLField(blank=True)),
                ('position', models.CharField(choices=[('HOME_TOP', 'Home - Top Banner'), ('HOME_SIDEBAR', 'Home - Sidebar'), ('DASHBOARD_TOP', 'Admin Dashboard - Top'), ('MOBILE_SPLASH', 'Mobile App - Splash'), ('OTHER', 'Other')], default='HOME_TOP', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Advert',
                'verbose_name_plural': 'Adverts',
                'db_table': 'bookutu_adverts',
                'ordering': ['-created_at'],
            },
        ),
    ]
