# Generated by Django 4.2.7 on 2025-10-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookutu', '0003_advert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='position',
        ),
    ]
