# Generated by Django 5.2.15 on 2026-07-04 20:12

import common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('departure_date', models.DateTimeField()),
                ('departure_time', models.CharField(max_length=20)),
                ('arrival_time', models.CharField(max_length=20)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='SCHEDULED', max_length=32)),
                ('available_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.bus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='companies.company')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='fleet.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='fleet.route')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPricing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('peak_season_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('demand_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('early_bird_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('early_bird_days', models.IntegerField(default=7)),
                ('final_base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='trips.trip')),
            ],
            options={
                'db_table': 'trip_pricing',
            },
        ),
    ]
