# Generated by Django 4.2.8 on 2025-09-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_fix_bus_schema'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['license_plate'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='registration_number',
            new_name='license_plate',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='manufacturer',
            new_name='make',
        ),
    ]
