# Generated by Django 4.2.8 on 2025-09-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('source', models.CharField(choices=[('MOBILE_APP', 'Mobile App'), ('WEB', 'Website'), ('DIRECT', 'Direct Booking'), ('PHONE', 'Phone Booking'), ('WALK_IN', 'Walk-in')], default='MOBILE_APP', max_length=20)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_phone', models.CharField(max_length=20)),
                ('passenger_email', models.EmailField(blank=True, max_length=254)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seat_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings_booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True)),
                ('cancellation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking Cancellation',
                'verbose_name_plural': 'Booking Cancellations',
                'db_table': 'bookings_cancellation',
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('MODIFIED', 'Modified'), ('COMPLETED', 'Completed')], max_length=20)),
                ('description', models.TextField()),
                ('previous_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Booking History',
                'verbose_name_plural': 'Booking Histories',
                'db_table': 'bookings_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='companies.busseat')),
            ],
            options={
                'verbose_name': 'Seat Reservation',
                'verbose_name_plural': 'Seat Reservations',
                'db_table': 'bookings_seat_reservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
