# Generated by Django 5.2.15 on 2026-07-04 20:12

import common.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=120)),
                ('make', models.CharField(max_length=120)),
                ('year', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('bus_type', models.CharField(max_length=120)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_charging_ports', models.BooleanField(default=False)),
                ('has_entertainment', models.BooleanField(default=False)),
                ('has_restroom', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='companies.company')),
            ],
            options={
                'db_table': 'buses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_number', models.CharField(max_length=120, unique=True)),
                ('license_expiry_date', models.DateTimeField()),
                ('date_of_birth', models.DateTimeField()),
                ('employee_id', models.CharField(blank=True, max_length=120, null=True)),
                ('hire_date', models.DateTimeField()),
                ('status', models.CharField(default='ACTIVE', max_length=32)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='companies.company')),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('origin_city', models.CharField(max_length=120)),
                ('origin_terminal', models.CharField(max_length=120)),
                ('destination_city', models.CharField(max_length=120)),
                ('destination_terminal', models.CharField(max_length=120)),
                ('distance_km', models.IntegerField()),
                ('estimated_duration_hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('intermediate_stops', models.JSONField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='companies.company')),
            ],
            options={
                'db_table': 'routes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=20)),
                ('row_number', models.IntegerField()),
                ('seat_position', models.CharField(max_length=20)),
                ('seat_type', models.CharField(max_length=50)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('has_extra_legroom', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=6)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='fleet.bus')),
            ],
            options={
                'db_table': 'bus_seats',
                'unique_together': {('bus', 'seat_number')},
            },
        ),
    ]
