# Generated by Django 5.2.15 on 2026-07-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='has_charging_ports',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='has_wifi',
        ),
    ]
