# Generated by Django 4.2.8 on 2025-09-02 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Uganda', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('license_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('logo', models.ImageField(blank=True, upload_to='companies/logos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='companies/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies_company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_booking_days', models.PositiveIntegerField(default=30)),
                ('cancellation_hours', models.PositiveIntegerField(default=24)),
                ('cancellation_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('accepts_cash', models.BooleanField(default=True)),
                ('accepts_mobile_money', models.BooleanField(default=True)),
                ('accepts_card', models.BooleanField(default=False)),
                ('send_sms_notifications', models.BooleanField(default=True)),
                ('send_email_notifications', models.BooleanField(default=True)),
                ('office_open_time', models.TimeField(default='08:00')),
                ('office_close_time', models.TimeField(default='18:00')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('cancellation_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
                'db_table': 'companies_settings',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('total_seats', models.PositiveIntegerField()),
                ('bus_type', models.CharField(choices=[('STANDARD', 'Standard'), ('LUXURY', 'Luxury'), ('VIP', 'VIP'), ('SLEEPER', 'Sleeper')], default='STANDARD', max_length=20)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_charging_ports', models.BooleanField(default=False)),
                ('has_entertainment', models.BooleanField(default=False)),
                ('has_restroom', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='buses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='companies.company')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
                'db_table': 'companies_bus',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('row_number', models.PositiveIntegerField()),
                ('seat_position', models.CharField(max_length=10)),
                ('seat_type', models.CharField(choices=[('REGULAR', 'Regular'), ('PREMIUM', 'Premium'), ('VIP', 'VIP')], default='REGULAR', max_length=20)),
                ('is_window', models.BooleanField(default=False)),
                ('is_aisle', models.BooleanField(default=False)),
                ('has_extra_legroom', models.BooleanField(default=False)),
                ('price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='companies.bus')),
            ],
            options={
                'verbose_name': 'Bus Seat',
                'verbose_name_plural': 'Bus Seats',
                'db_table': 'companies_bus_seat',
                'ordering': ['row_number', 'seat_position'],
                'unique_together': {('bus', 'seat_number')},
            },
        ),
    ]
