# Generated by Django 4.2.8 on 2025-09-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('COMPANY_STAFF', 'Company Staff'), ('SUPER_ADMIN', 'Super Admin')], default='COMPANY_STAFF', max_length=20),
        ),
    ]
