# Generated by Django 4.2.7 on 2025-10-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('COMPANY_STAFF', 'Company Staff'), ('SUPER_ADMIN', 'Super Admin'), ('PASSENGER', 'Passenger')], default='COMPANY_STAFF', max_length=20),
        ),
    ]
