# Generated by Django 5.2.15 on 2026-07-22 16:10

import common.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=common.ids.generate_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=150)),
                ('sender_phone', models.CharField(max_length=30)),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=30)),
                ('origin_terminal', models.CharField(max_length=150)),
                ('destination_terminal', models.CharField(max_length=150)),
                ('package_description', models.CharField(max_length=255)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('PICKED_UP', 'Picked up'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='companies.company')),
                ('picked_up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_deliveries', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliveries',
                'ordering': ['-created_at'],
            },
        ),
    ]
