# Generated by Django 5.2.15 on 2026-07-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('ON_DELIVERY', 'On delivery'), ('PICKED_UP', 'Picked up'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20),
        ),
    ]
