// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABF3Bahjqgj1xpryJ1uxBUe5ULmsf3C3k',
    appId: '1:669236525864:web:600d60351738acdfb2ee1d',
    messagingSenderId: '669236525864',
    projectId: 'bookutu-busapp',
    authDomain: 'bookutu-busapp.firebaseapp.com',
    storageBucket: 'bookutu-busapp.firebasestorage.app',
    measurementId: 'G-2YN3WH98P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8fxzkt0fZxjjKxbsbs7ISKmWd4knYHJ0',
    appId: '1:669236525864:android:ca1a5f923a0ae2e6b2ee1d',
    messagingSenderId: '669236525864',
    projectId: 'bookutu-busapp',
    storageBucket: 'bookutu-busapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_u6fcjvGkWpXRhZIY6NLnaTViYR9BP4',
    appId: '1:669236525864:ios:44c808d4f6b99031b2ee1d',
    messagingSenderId: '669236525864',
    projectId: 'bookutu-busapp',
    storageBucket: 'bookutu-busapp.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ_u6fcjvGkWpXRhZIY6NLnaTViYR9BP4',
    appId: '1:669236525864:ios:44c808d4f6b99031b2ee1d',
    messagingSenderId: '669236525864',
    projectId: 'bookutu-busapp',
    storageBucket: 'bookutu-busapp.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABF3Bahjqgj1xpryJ1uxBUe5ULmsf3C3k',
    appId: '1:669236525864:web:3d9e8908cf811713b2ee1d',
    messagingSenderId: '669236525864',
    projectId: 'bookutu-busapp',
    authDomain: 'bookutu-busapp.firebaseapp.com',
    storageBucket: 'bookutu-busapp.firebasestorage.app',
    measurementId: 'G-8NFSNDP4LG',
  );
}
